# Generated by Django 3.0.2 on 2020-05-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pythoncode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.EmailField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10000)),
            ],
        ),
    ]
