# Generated by Django 3.0.2 on 2020-05-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pythoncode',
            name='code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pythoncode',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
